server.port: 9995

security:
  ignored: /open,/sdoc.jsp,/*.js,/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*,/v2/api-docs

spring.oauth2.resource:
  id: cloud_controller
  jwt:
    keyUri: ${TOKEN_KEY}

services:
  catalog: http://localhost:9991
  catalogUser: admin
  catalogPass: password

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

maximum_cache_size: 1000
cache_expiration_time_s: 60

endpoints.enabled: false
endpoints.health.enabled: true
