sync:
  delay_seconds: 60

services:
  catalog: http://localhost:9991
  catalogUser: admin
  catalogPass: password

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

maximum_cache_size: 1000
cache_expiration_time_s: 60

endpoints.enabled: false
endpoints.health.enabled: true
