sync:
  delay_seconds: 60

services:
  catalog:
    url: http://${CATALOG_HOST:localhost}:${CATALOG_PORT:9991}
    user: ${CATALOG_USER:admin}
    pass: ${CATALOG_PASS:password}
    hostname_key: hostname
    login_key: login
    pass_key: password
    core_organization_uuid: ${CORE_ORGANIZATION_UUID}
  model_catalog:
    url: http://${MODEL_CATALOG_HOST:localhost}:${MODEL_CATALOG_PORT:9992}
  redis:
    url: ${REDIS_HOST:localhost}:${REDIS_PORT:6379}
    collection: models

spring.oauth2:
  client:
    id: tap
    accessTokenUri: ${TOKEN_URI}
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

maximum_cache_size: 1000
cache_expiration_time_s: 60
