sync:
  delay_seconds: 60

services:
  catalog:
    url: http://${catalogHost:localhost}:${catalogPort:9991}
    user: ${catalogUser:admin}
    pass: ${catalogPass:password}
    hostname_key: hostname
    login_key: login
    pass_key: password


logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

maximum_cache_size: 1000
cache_expiration_time_s: 60

endpoints.enabled: false
endpoints.health.enabled: true
