sync:
  delay_seconds: 60

services:
  catalog:
    url: http://${catalogHost:localhost}:${catalogPort:9991}
    user: ${catalogUser:admin}
    pass: ${catalogPass:password}
    hostname_key: hostname
    login_key: login
    pass_key: password
    core_organization_uuid: ${coreOrganizationUuid}
  model_catalog:
    url: http://${modelCatalogHost:localhost}:${modelCatalogPort:9992}
  redis:
    url: ${redisHost:localhost}:${redisPort:6379}
    collection: models

spring.oauth2:
  client:
    id: tap
    accessTokenUri: ${tokenUri}
    clientId: ${clientId}
    clientSecret: ${clientSecret}

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

maximum_cache_size: 1000
cache_expiration_time_s: 60
